name: Snyk Docker Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  snyk-docker-scan:
    name: Snyk Docker Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install snyk CLI
        run: |
          npm install -g snyk
          snyk --version  # Verify snyk installation

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Auth with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Build & Scan Microservices
        run: |
          services=(auth-service user-service product-service)

          for service in "${services[@]}"
          do
            path="backend/$service"
            echo "🔨 Building image for $service from $path..."
            docker build -t $service:latest "$path"

            echo "🔍 Scanning $service image with Snyk..."
            snyk test --docker $service:latest --file="$path/Dockerfile" --severity-threshold=high || true
          done
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Done
        run: echo "✅ All images scanned"
